// This file is generated by scripts/generate-data-registry.mjs.
// Do not edit it by hand.
import dailyArtifact0 from "../data/daily-factors/2026-08-24.json";
import validationArtifact0 from "../data/validations/2026-07-14.json";
import validationArtifact1 from "../data/validations/2026-07-15.json";
import validationArtifact2 from "../data/validations/2026-07-16.json";
import validationArtifact3 from "../data/validations/2026-07-18.json";
import validationArtifact4 from "../data/validations/2026-07-21.json";
import validationArtifact5 from "../data/validations/2026-07-22.json";
import validationArtifact6 from "../data/validations/2026-07-23.json";
import validationArtifact7 from "../data/validations/2026-07-24.json";
import validationArtifact8 from "../data/validations/2026-07-25.json";
import validationArtifact9 from "../data/validations/2026-07-26.json";
import validationArtifact10 from "../data/validations/2026-07-27.json";
import validationArtifact11 from "../data/validations/2026-07-28.json";
import validationArtifact12 from "../data/validations/2026-07-29.json";
import validationArtifact13 from "../data/validations/2026-07-30.json";
import validationArtifact14 from "../data/validations/2026-07-31.json";
import validationArtifact15 from "../data/validations/2026-08-01.json";
import validationArtifact16 from "../data/validations/2026-08-02.json";
import validationArtifact17 from "../data/validations/2026-08-03.json";
import validationArtifact18 from "../data/validations/2026-08-04.json";
import validationArtifact19 from "../data/validations/2026-08-05.json";
import validationArtifact20 from "../data/validations/2026-08-06.json";
import validationArtifact21 from "../data/validations/2026-08-07.json";
import validationArtifact22 from "../data/validations/2026-08-08.json";
import validationArtifact23 from "../data/validations/2026-08-09.json";
import validationArtifact24 from "../data/validations/2026-08-10.json";
import validationArtifact25 from "../data/validations/2026-08-11.json";
import validationArtifact26 from "../data/validations/2026-08-12.json";
import validationArtifact27 from "../data/validations/2026-08-13.json";
import validationArtifact28 from "../data/validations/2026-08-14.json";
import validationArtifact29 from "../data/validations/2026-08-15.json";
import validationArtifact30 from "../data/validations/2026-08-16.json";
import validationArtifact31 from "../data/validations/2026-08-17.json";
import validationArtifact32 from "../data/validations/2026-08-18.json";
import validationArtifact33 from "../data/validations/2026-08-19.json";
import validationArtifact34 from "../data/validations/2026-08-20.json";
import validationArtifact35 from "../data/validations/2026-08-23.json";
import validationArtifact36 from "../data/validations/2026-08-24.json";

export const dailyArtifacts = {
  "2026-08-24": dailyArtifact0,
} as const;

export const validationArtifacts = {
  "2026-07-14": validationArtifact0,
  "2026-07-15": validationArtifact1,
  "2026-07-16": validationArtifact2,
  "2026-07-18": validationArtifact3,
  "2026-07-21": validationArtifact4,
  "2026-07-22": validationArtifact5,
  "2026-07-23": validationArtifact6,
  "2026-07-24": validationArtifact7,
  "2026-07-25": validationArtifact8,
  "2026-07-26": validationArtifact9,
  "2026-07-27": validationArtifact10,
  "2026-07-28": validationArtifact11,
  "2026-07-29": validationArtifact12,
  "2026-07-30": validationArtifact13,
  "2026-07-31": validationArtifact14,
  "2026-08-01": validationArtifact15,
  "2026-08-02": validationArtifact16,
  "2026-08-03": validationArtifact17,
  "2026-08-04": validationArtifact18,
  "2026-08-05": validationArtifact19,
  "2026-08-06": validationArtifact20,
  "2026-08-07": validationArtifact21,
  "2026-08-08": validationArtifact22,
  "2026-08-09": validationArtifact23,
  "2026-08-10": validationArtifact24,
  "2026-08-11": validationArtifact25,
  "2026-08-12": validationArtifact26,
  "2026-08-13": validationArtifact27,
  "2026-08-14": validationArtifact28,
  "2026-08-15": validationArtifact29,
  "2026-08-16": validationArtifact30,
  "2026-08-17": validationArtifact31,
  "2026-08-18": validationArtifact32,
  "2026-08-19": validationArtifact33,
  "2026-08-20": validationArtifact34,
  "2026-08-23": validationArtifact35,
  "2026-08-24": validationArtifact36,
} as const;
