// This file is generated by scripts/generate-data-registry.mjs.
// Do not edit it by hand.
import dailyArtifact0 from "../data/daily-factors/2026-07-15.json";
import validationArtifact0 from "../data/validations/2026-07-14.json";

export const dailyArtifacts = {
  "2026-07-15": dailyArtifact0,
} as const;

export const validationArtifacts = {
  "2026-07-14": validationArtifact0,
} as const;
